language: ruby
cache: bundler
bundler_args: --without development
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.1
- ruby-head
- rbx
env: CI="travis"
sudo: false
os:
- linux
dist: trusty
matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: rbx
  fast_finish: true
install:
- wget -O aerospike-server.tgz http://aerospike.com/download/server/latest/artifact/tgz
- tar xvzf aerospike-server.tgz
- cp -f .travis/aerospike.conf ./aerospike-server/share/etc
- cd aerospike-server
- sed -i -e 's/\${me}/"root"/' share/libexec/aerospike-start
- sed -i -e 's/set_shmmax$/#set_shmmax/' share/libexec/aerospike-start
- sed -i -e 's/set_shmall$/#set_shmall/' share/libexec/aerospike-start
- mkdir instance1
- mkdir instance2
- ./bin/aerospike init --home instance1 --instance 1 --service-port 3000
- ./bin/aerospike init --home instance2 --instance 2 --service-port 3010
- cd instance1
- ./bin/aerospike start
- ../../scripts/wait-for-node.sh var/log/aerospike.log
- cd ..
- cd instance2
- ./bin/aerospike start
- ../../scripts/wait-for-node.sh var/log/aerospike.log
- cd ../..
script:
- bundle install
- bundle exec rspec
notifications:
  hipchat:
    rooms:
      secure: H5qTvLxIBBinW4eE6D/x1+BBLUeOb+7dq3wkgSR8IUTGoBZ2bbVWwqNbKUJ1ueuKs4g9RvV7sDkG03dSze/lZJcE+bOMfIGkmBRl0InnTZdGvAs9QD2DCs6d+iNWBM9OvIPvjyTBJ2ryhmYcB2NFr2Nubl0xgdzFJA2BOAvHLK0=
  slack:
    secure: eTiZiYHWKgwzvR0VksJgaR3fOK4+HTT4vN+3N8/n4RUXAnzEEurvpAbwFwF0e47a5Pt1ro731Je/lgO6BXWsa8Cy/ZtuF/33VhKSaWsMopYfOcoGpGyc8GH3pz/7fnT9kz/f6ZSGpp+BV+hK8dYu3x5kKWCQ7VTq33CNEYLmcow=
  email:
  - qe-notices@aerospike.com
  - qe-notices-clients@aerospike.com
